//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppExamen.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaciones
    {
        public int ID_Asignacion { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Proyecto { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
